api:
  path:
    default: /v1/api

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081

---

spring.profiles: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/blog?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: deviation-365
    password: prod1005!
    driver-class-name: com.mysql.cj.jdbc.Driver

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolname: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: SELECT 1
